'use client'

import { useEffect, useState, useRef } from 'react'
import Link from 'next/link'
import Image from 'next/image'

const safetyPhases = [
  {
    title: 'Teach',
    body: 'We start by teaching our AI right from wrong, filtering harmful content and responding with empathy.',
    detail: 'Using curated datasets, we apply rigorous deduplication and safety filtering. We also augment this with 112B high-quality synthetic tokens generated by safety-aligned teacher models to ensure a robust foundation.',
    overlayTitle: 'Teaching models to respond safely',
    image: '/model-images/ngen4.png',
    icon: 'teach',
    points: [
      'Strict deduplication and quality filtering of open-source datasets.',
      'Comprehensive safety filtering for CSAM, violence, and hate speech.',
      'Data augmentation with high-fidelity, safety-aligned synthetic tokens.',
    ],
  },
  {
    title: 'Test',
    body: 'We conduct internal evaluations and work with experts to test real-world scenarios, enhancing our safeguards.',
    detail: 'Instruction tuning ensures the model aligns with human intent. We use feedback from beta models like ngen4-atom-chat to iteratively improve responsiveness and context-awareness in multi-turn conversations.',
    overlayTitle: 'Testing before and after release',
    image: '/model-images/ngen4-pro.png',
    icon: 'test',
    points: [
      'Instruct and agentic tuning for real-world application reliability.',
      'Iterative refinement based on beta feedback and edge-case testing.',
      'Training for structured, step-by-step reasoning to reduce logic leaps.',
    ],
  },
  {
    title: 'Share',
    body: 'We use real-world feedback to help make our AI safer and more helpful.',
    detail: 'Reinforcement Learning from Human Feedback aligns model outputs with strict safety guidelines and objectivity. During this phase, we calibrate our new Reasoning Mode across Low, Medium, and High tiers.',
    overlayTitle: 'Learning from real-world use',
    image: '/ai-safety.png',
    icon: 'share',
    points: [
      'Calibrating dynamic reasoning tiers for safety and efficiency.',
      'Active penalization of biased, toxic, or hallucinated content.',
      'Teacher In-Loop alignment to prevent misaligned or "Shoggoth" behaviors.',
    ],
  },
]

const protectionAreas = [
  {
    title: 'Child safety',
    body: 'Reducing harmful content, escalation risk, and unsafe guidance for younger users.',
    detail: 'We design stricter behavior around child safety, including refusal patterns, escalation review, and safeguards for content that may involve exploitation, grooming, coercion, or self-harm risk.',
    overlayTitle: 'Working together to keep children safe',
    icon: 'child',
    points: [
      'Prevent: Filtering child sexual abuse material in training and product flows.',
      'Protect: Blocking attempts to generate sexual content involving minors.',
      'Improve: Strengthening safeguards as new misuse patterns appear.',
    ],
  },
  {
    title: 'Private information',
    body: 'Limiting the exposure of personal data and improving privacy-preserving model behavior.',
    detail: 'NGen systems are guided to avoid revealing private data, reduce over-collection, and be careful around identifiers, credentials, and sensitive information.',
    overlayTitle: 'Protecting private information',
    icon: 'privacy',
    points: [
      'Reducing unnecessary collection and exposure of sensitive personal info.',
      'Stricter care for credentials, medical details, and financial identifiers.',
      'Training models to avoid requesting private data unnecessarily.',
    ],
  },
  {
    title: 'Deep fakes',
    body: 'Building detection, provenance, and refusal patterns for deceptive synthetic media.',
    detail: 'We focus on reducing impersonation and deception by guiding models away from harmful requests involving fake identities or manipulated evidence.',
    overlayTitle: 'Reducing deceptive synthetic media',
    icon: 'deepfake',
    points: [
      'Refusing requests that enable impersonation, fraud, or fabricated evidence.',
      'Supporting safer provenance and detection workflows.',
      'Reviewing multimodal models for misleading identity and consent risks.',
    ],
  },
  {
    title: 'Bias',
    body: 'Evaluating model behavior across languages, cultures, and sensitive decision contexts.',
    detail: 'Bias work includes multilingual evaluation, prompt audits, and scenario reviews that look for unfair treatment or stereotype reinforcement.',
    overlayTitle: 'Evaluating bias across contexts',
    icon: 'bias',
    points: [
      'Testing across languages, regions, and demographic-sensitive scenarios.',
      'Reducing stereotype reinforcement and inconsistent treatment.',
      'Avoiding reliance on models for high-impact decisions without human review.',
    ],
  },
  {
    title: 'Elections',
    body: 'Reducing manipulation, impersonation, and misleading political information.',
    detail: 'Election safeguards focus on civic integrity: resisting impersonation, deceptive persuasion, and false procedural claims.',
    overlayTitle: 'Supporting civic integrity',
    icon: 'elections',
    points: [
      'Reducing misleading procedural claims about voting and registration.',
      'Blocking impersonation and deceptive campaign-style misuse.',
      'Prioritizing reliable, neutral civic information in model behavior.',
    ],
  },
]

const learnMoreCards = [
  { title: 'NGen 4 System Card', label: 'System Card', date: 'Model safety', href: '/company/news/ngen-4-system-card', image: '/ngen4-sys-card.png' },
  { title: 'NGen 3 System Card', label: 'System Card', date: 'PDF', href: '/NGen3%20System%20Card.pdf', image: '/ngen3-sys-card.png', external: true },
  { title: 'Open-Sourcing NGen-4-K2-1T-Thinking', label: 'Open Source', date: 'NGen release', href: '/company/news/ngen-4-k2-1t-thinking-open-source', image: '/TV - 4.svg' },
]

const deepSafetyLinks = [
  { title: 'NGen 4 System Card', href: '/company/news/ngen-4-system-card' },
  { title: 'Advanced Algorithmic Paradigms for Artificial Superintelligence', href: '/research/advanced-algorithmic-paradigms-asi' },
  { title: 'Interpretable Attention Visualization Module', href: '/research/interpretable-attention-visualization-module' },
  { title: 'Agentic Intelligence and NGen 3.9 Pro', href: '/research/agentic-intelligence-ngen39-pro' },
  { title: 'Computational Hardware and Data Foundations for Sustainable Superintelligence', href: '/research/computational-hardware-and-data-foundations-for-sustainable-superintelligence' },
]

type SafetyOverlay = { eyebrow: string; title: string; body: string; points: string[]; image?: string; icon: string }

function useReveal() {
  const ref = useRef<HTMLDivElement>(null)
  const [v, setV] = useState(false)
  useEffect(() => {
    const el = ref.current; if (!el) return
    const o = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setV(true); o.disconnect() } }, { threshold: 0.12 })
    o.observe(el); return () => o.disconnect()
  }, [])
  return { ref, cls: `transition-all duration-700 ease-out ${v ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}` }
}

function PhaseIcon({ type, className }: { type: string, className?: string }) {
  const c = className || "w-16 h-16 stroke-black/80"
  if (type === 'teach') return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" /></svg>
  if (type === 'test') return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" /><path d="M9 12l2 2 4-4" /></svg>
  if (type === 'share') return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1"><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><line x1="8.59" y1="13.51" x2="15.42" y2="17.49" /><line x1="15.41" y1="6.51" x2="8.59" y2="10.49" /></svg>
  return null
}

function ProtectionIcon({ type }: { type: string }) {
  const c = "w-8 h-8 stroke-black/80"
  if (type === 'child') return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="9" cy="7" r="3" /><circle cx="17" cy="7" r="3" /><path d="M3 21v-2a4 4 0 014-4h4a4 4 0 014 4v2" /><path d="M17 11a4 4 0 014 4v2" /></svg>
  if (type === 'privacy') return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="3" y="11" width="18" height="11" rx="2" /><path d="M7 11V7a5 5 0 0110 0v4" /><circle cx="12" cy="16" r="1" /></svg>
  if (type === 'deepfake') return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="12" cy="8" r="5" /><path d="M3 21v-2a7 7 0 0114 0v2" /><path d="M16 3l5 5M21 3l-5 5" /></svg>
  if (type === 'bias') return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 3v18M3 12h18" /><circle cx="7" cy="7" r="2" /><circle cx="17" cy="7" r="2" /><circle cx="7" cy="17" r="2" /><circle cx="17" cy="17" r="2" /></svg>
  return <svg className={c} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="3" y="3" width="18" height="18" rx="2" /><path d="M9 12l2 2 4-4" /></svg>
}

function PipelineDiagram() {
  const r = useReveal()
  return (
    <div ref={r.ref} className={`py-20 ${r.cls}`}>
      <div className="relative w-full max-w-[860px] mx-auto">
        <Image src="/training-flow.png" alt="NGen 4 training pipeline" width={1720} height={1080} quality={100} className="w-full h-auto" sizes="(min-width: 1024px) 860px, calc(100vw - 40px)" />
      </div>
    </div>
  )
}

export default function SafetyPage() {
  const [activeOverlay, setActiveOverlay] = useState<SafetyOverlay | null>(null)
  const s1 = useReveal(), s2 = useReveal(), s3 = useReveal(), s4 = useReveal(), s5 = useReveal()

  useEffect(() => {
    if (!activeOverlay) { document.body.style.overflow = ''; return }
    document.body.style.overflow = 'hidden'
    const h = (e: KeyboardEvent) => { if (e.key === 'Escape') setActiveOverlay(null) }
    window.addEventListener('keydown', h)
    return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', h) }
  }, [activeOverlay])

  return (
    <div className="min-h-screen bg-white text-black pt-[150px]">
      {/* Hero Poster - Sized as requested */}
      <section ref={s1.ref} className={`mb-32 ${s1.cls}`}>
        <div className="relative w-full max-w-[860px] mx-auto mb-12 aspect-[1028/560] overflow-hidden rounded-lg bg-gray-50 border border-gray-100">
          <Image src="/ai-safety.png" alt="AI Safety" fill priority quality={100} className="object-cover" sizes="(min-width: 1024px) 860px, calc(100vw - 40px)" />
        </div>
      </section>

      <main className="mx-auto max-w-[920px] px-5 pb-24">
        {/* Phase Cards with Static Icons */}
        <section ref={s2.ref} className={`mb-32 grid gap-8 md:grid-cols-3 ${s2.cls}`}>
          {safetyPhases.map((phase) => (
            <div key={phase.title} className="group flex flex-col rounded-2xl border border-gray-100 bg-white p-6 transition-all hover:border-gray-200">
              <h2 className="mb-6 text-[20px] font-semibold text-gray-900">{phase.title}</h2>
              <div className="relative aspect-square w-full overflow-hidden rounded-xl bg-gray-50 flex items-center justify-center">
                <PhaseIcon type={phase.icon} />
              </div>
              <p className="mt-6 flex-1 text-[14px] leading-6 text-gray-600">{phase.body}</p>
              <button type="button" onClick={() => setActiveOverlay({ eyebrow: phase.title, title: phase.overlayTitle, body: phase.detail, points: phase.points, image: phase.image, icon: phase.icon })}
                className="mt-6 inline-flex h-9 w-9 items-center justify-center rounded-full bg-black text-white transition-all hover:scale-110" aria-label={`Read more about ${phase.title}`}>
                <span className="text-xl leading-none font-light">+</span>
              </button>
            </div>
          ))}
        </section>

        {/* Pipeline Section */}
        <section className="mb-32">
          <div className="text-center mb-12">
            <h2 className="text-[36px] font-medium tracking-tight">An engineering loop</h2>
            <p className="mx-auto mt-4 max-w-[600px] text-gray-600 leading-7">
              Safety isn&apos;t a final step. It&apos;s a continuous engineering cycle of training, testing, and alignment that powers every release of NGen 4.
            </p>
          </div>
          <PipelineDiagram />
        </section>

        {/* Protection Areas */}
        <section ref={s3.ref} className={`mb-32 ${s3.cls}`}>
          <div className="mb-12 text-center">
            <h2 className="text-[36px] font-medium tracking-tight">Protecting people where it matters most</h2>
            <p className="mx-auto mt-4 max-w-[640px] text-gray-600 leading-7">
              We focus our safety research and deployment guardrails on high-stakes areas that impact individuals and society.
            </p>
          </div>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {protectionAreas.slice(0, 3).map((a) => (
              <div key={a.title} className="rounded-2xl border border-gray-100 bg-white p-8 transition-all hover:border-gray-200">
                <ProtectionIcon type={a.icon} />
                <h3 className="mt-6 text-[20px] font-semibold text-gray-900">{a.title}</h3>
                <p className="mt-3 text-[14px] leading-6 text-gray-600">{a.body}</p>
                <button type="button" onClick={() => setActiveOverlay({ eyebrow: a.title, title: a.overlayTitle, body: a.detail, points: a.points, icon: a.icon })}
                  className="mt-6 inline-flex h-8 w-8 items-center justify-center rounded-full bg-black text-white transition-all hover:scale-110" aria-label={`Read more about ${a.title}`}>
                  <span className="text-lg leading-none font-light">+</span>
                </button>
              </div>
            ))}
          </div>
          <div className="grid gap-6 sm:grid-cols-2 mt-6">
            {protectionAreas.slice(3).map((a) => (
              <div key={a.title} className="rounded-2xl border border-gray-100 bg-white p-8 transition-all hover:border-gray-200">
                <ProtectionIcon type={a.icon} />
                <h3 className="mt-6 text-[20px] font-semibold text-gray-900">{a.title}</h3>
                <p className="mt-3 text-[14px] leading-6 text-gray-600">{a.body}</p>
                <button type="button" onClick={() => setActiveOverlay({ eyebrow: a.title, title: a.overlayTitle, body: a.detail, points: a.points, icon: a.icon })}
                  className="mt-6 inline-flex h-8 w-8 items-center justify-center rounded-full bg-black text-white transition-all hover:scale-110" aria-label={`Read more about ${a.title}`}>
                  <span className="text-lg leading-none font-light">+</span>
                </button>
              </div>
            ))}
          </div>
        </section>

        {/* Learn More */}
        <section ref={s4.ref} className={`mb-32 ${s4.cls}`}>
          <div className="mb-10 flex items-center justify-between border-b border-gray-100 pb-6">
            <h2 className="text-[24px] font-semibold">Latest safety research</h2>
            <Link href="/company/news" className="text-sm font-medium text-gray-500 hover:text-black transition-colors">View all news →</Link>
          </div>
          <div className="grid gap-10 md:grid-cols-3">
            {learnMoreCards.map((card) => (
              <Link key={card.title} href={card.href} target={card.external ? '_blank' : undefined} rel={card.external ? 'noopener noreferrer' : undefined} className="group block">
                <div className="relative aspect-[16/10] overflow-hidden rounded-lg bg-gray-100 border border-gray-50">
                  <Image src={card.image} alt={card.title} fill quality={100} className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="320px" />
                </div>
                <div className="mt-6">
                  <div className="flex items-center gap-3 text-[12px] font-medium text-gray-400 tracking-tight mb-2">
                    <span>{card.label}</span>
                    <span className="w-1 h-1 rounded-full bg-gray-200" />
                    <span>{card.date}</span>
                  </div>
                  <h3 className="text-[18px] font-semibold leading-snug group-hover:text-gray-600 transition-colors">{card.title}</h3>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* Footer Links */}
        <section ref={s5.ref} className={`border-t border-gray-100 pt-16 ${s5.cls}`}>
          <h2 className="mb-10 text-[32px] font-medium">Dive deeper into NGen 4 safety.</h2>
          <div className="grid gap-4">
            {deepSafetyLinks.map((item) => (
              <Link key={item.title} href={item.href} className="group flex items-center justify-between p-6 rounded-2xl border border-gray-100 bg-gray-50/50 hover:bg-white hover:border-gray-200 transition-all">
                <span className="text-[17px] font-medium text-gray-800 group-hover:text-black">{item.title}</span>
                <span className="text-sm font-medium text-gray-400 group-hover:text-black transition-colors">Read more →</span>
              </Link>
            ))}
          </div>
        </section>
      </main>

      {/* Full-Screen Overlay */}
      {activeOverlay && (
        <div className="fixed inset-0 z-[100] bg-white overflow-y-auto" style={{ animation: 'overlayFadeIn 0.4s ease-out' }} role="dialog" aria-modal="true" aria-labelledby="safety-overlay-title">
          <button type="button" onClick={() => setActiveOverlay(null)} className="fixed right-8 top-8 z-[110] flex h-12 w-12 items-center justify-center rounded-full bg-gray-50 text-gray-400 hover:text-black hover:bg-gray-100 transition-all">
            <span className="text-3xl leading-none">&times;</span>
          </button>

          <div className="relative mx-auto flex min-h-screen max-w-[900px] flex-col items-center justify-center px-6 py-32" style={{ animation: 'overlaySlideUp 0.6s cubic-bezier(0.16, 1, 0.3, 1)' }}>
            <p className="mb-8 text-sm font-semibold text-gray-400 tracking-tight text-center">{activeOverlay.eyebrow}</p>
            <h2 id="safety-overlay-title" className="text-center text-[40px] md:text-[64px] font-medium leading-[1.1] tracking-tight text-gray-900 mb-16">{activeOverlay.title}</h2>

            <div className="grid gap-16 lg:grid-cols-[1.2fr_1fr] items-center w-full mb-20">
              <div className="relative aspect-square w-full rounded-3xl bg-gray-50 overflow-hidden flex items-center justify-center border border-gray-100">
                <PhaseIcon type={activeOverlay.icon} className="w-32 h-32 stroke-black/80" />
              </div>
              <div className="text-[20px] leading-9 text-gray-600 font-light">
                {activeOverlay.body}
              </div>
            </div>

            <div className="w-full">
              <h3 className="text-[24px] font-medium mb-10">Key safeguards</h3>
              <ul className="grid gap-8 sm:grid-cols-2">
                {activeOverlay.points.map((p, idx) => (
                  <li key={idx} className="flex gap-6 text-gray-600 leading-8 items-start">
                    <span className="flex-shrink-0 w-8 h-8 rounded-full border border-gray-100 flex items-center justify-center text-[12px] font-bold text-black mt-1">{idx + 1}</span>
                    <span className="text-[17px]">{p}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}
      <style>{`
        @keyframes overlayFadeIn { from { opacity: 0; } to { opacity: 1; } }
        @keyframes overlaySlideUp { from { opacity: 0; transform: translateY(60px); } to { opacity: 1; transform: translateY(0); } }
      `}</style>
    </div>
  )
}
