import type { Metadata } from 'next'
import LegalDocument, { type LegalSection } from '@/components/LegalDocument'

export const metadata: Metadata = {
  title: 'Model Complaints | TNSA',
  description: 'How to report and appeal concerns about TNSA model behavior or output.',
}

const sections: LegalSection[] = [
  {
    title: 'What this process covers',
    paragraphs: [
      'Use this process to report concerns about output generated by a TNSA-hosted model, including potentially unlawful, unsafe, discriminatory, privacy-invasive, infringing, or persistently inaccurate behavior.',
      'For account access, billing, or ordinary technical issues, contact general support instead. If there is an immediate threat to life or safety, contact local emergency services first.',
    ],
  },
  {
    title: 'Submit a complaint',
    paragraphs: ['Send the report from an email address where we can reach you. Include as much of the following as is safely available:'],
    bullets: [
      'The product, model name, model version, and approximate date and time of the interaction.',
      'The prompt or input, relevant output, and any steps needed to reproduce the issue.',
      'A clear explanation of the concern and who may be affected.',
      'Screenshots, request IDs, or links that help us locate the interaction.',
      'Whether the report involves personal data, a minor, an urgent safety risk, or confidential material.',
    ],
  },
  {
    title: 'How we review reports',
    paragraphs: [
      'We triage complaints based on severity, scope, reproducibility, and potential impact. Review may involve safety, engineering, legal, privacy, and product teams. We may ask for additional information or a safer redacted example.',
      'Submitting a complaint does not guarantee a particular outcome, but credible reports inform investigations, evaluations, mitigations, and future model improvements.',
    ],
  },
  {
    title: 'Possible outcomes',
    paragraphs: ['Depending on the findings, we may take one or more actions:'],
    bullets: [
      'Provide guidance, clarification, or a product workaround.',
      'Adjust classifiers, prompts, filters, access controls, or product behavior.',
      'Add an issue to model evaluations or future training and safety work.',
      'Restrict content, an account, or a feature where our policies require it.',
      'Preserve information or notify relevant parties where required by law.',
    ],
  },
  {
    title: 'Privacy and confidentiality',
    paragraphs: [
      'Do not send passwords, access tokens, full payment details, or unnecessary sensitive data. We use complaint information to investigate and respond, and may retain it for safety, legal, and audit purposes.',
    ],
  },
  {
    title: 'Requesting reconsideration',
    paragraphs: [
      'If you disagree with the response, reply to the case email and explain what you believe was overlooked. Include new evidence where possible. A reviewer not responsible for the original decision may reassess eligible cases.',
    ],
  },
]

export default function ModelComplaintsPage() {
  return (
    <LegalDocument
      title="Model Complaints"
      summary="A clear route for reporting harmful, unlawful, inaccurate, or otherwise concerning model behavior."
      sections={sections}
      contactSubject="Model complaint"
    />
  )
}
